export const influencers = [
  {
    name: "John Doe",
    handle: "@johndoe",
    followers: 10000,
    reach: 20000,
    rating: "4.8",
    bio: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia quas veniam ut, dicta in dolorum minus facilis architecto rerum consequuntur possimus porro voluptate ab fuga beatae sit quisquam enim nemo! Perferendis, adipisci.",
    jobsCompleted: 10,
    successRate: "100%",
    profilePic:
      "https://img.freepik.com/premium-photo/stylish-man-flat-vector-profile-picture-ai-generated_606187-310.jpg",
    collaborationType: "Paid",
    engagement: 5000,
    media: [
      "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      "https://picsum.photos/200/300",
    ],
  },
  {
    name: "Jane Smith",
    handle: "@janesmith",
    followers: 12000,
    reach: 22000,
    rating: "4.9",
    bio: "Passionate traveler and lifestyle influencer with a flair for fashion. Helping others discover the beauty of the world!",
    jobsCompleted: 12,
    successRate: "95%",
    profilePic:
      "https://img.freepik.com/premium-photo/stylish-man-flat-vector-profile-picture-ai-generated_606187-310.jpg",
    collaborationType: "Paid",
    engagement: 6000,
    media: [
      "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      "https://picsum.photos/200/300",
    ],
  },
  {
    name: "Michael Jordan",
    handle: "@michaelj",
    followers: 8000,
    reach: 15000,
    rating: "4.7",
    bio: "Fitness enthusiast and personal trainer. Let's reach your goals together, one workout at a time!",
    jobsCompleted: 15,
    successRate: "98%",
    profilePic:
      "https://img.freepik.com/premium-photo/stylish-man-flat-vector-profile-picture-ai-generated_606187-310.jpg",
    collaborationType: "Unpaid",
    engagement: 4000,
    media: [
      "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      "https://picsum.photos/200/300",
    ],
  },
  {
    name: "Emily Brown",
    handle: "@emilyb",
    followers: 25000,
    reach: 30000,
    rating: "4.6",
    bio: "Lifestyle and beauty blogger. Sharing my favorite products, tips, and experiences with my amazing audience!",
    jobsCompleted: 18,
    successRate: "90%",
    profilePic:
      "https://img.freepik.com/premium-photo/stylish-man-flat-vector-profile-picture-ai-generated_606187-310.jpg",
    collaborationType: "Paid",
    engagement: 7500,
    media: [
      "https://fastly.picsum.photos/id/570/200/300.jpg?hmac=fMlqjNmBSgN75P_tCU-PVSGzRYQxU23Xqd593HxZSZQ",
    ],
  },
  {
    name: "Chris Wilson",
    handle: "@chrisw",
    followers: 6000,
    reach: 12000,
    rating: "4.9",
    bio: "Foodie and chef sharing delicious recipes and food experiences from around the world. Let's cook!",
    jobsCompleted: 8,
    successRate: "99%",
    profilePic:
      "https://img.freepik.com/premium-photo/stylish-man-flat-vector-profile-picture-ai-generated_606187-310.jpg",
    collaborationType: "Unpaid",
    engagement: 3000,
    media: [
      "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      "https://picsum.photos/200/300",
    ],
  },
  {
    name: "Lisa Johnson",
    handle: "@lisaj",
    followers: 30000,
    reach: 40000,
    rating: "4.8",
    bio: "Fashion and makeup artist bringing you the latest trends. Stay stylish with me!",
    jobsCompleted: 20,
    successRate: "100%",
    profilePic:
      "https://img.freepik.com/premium-photo/stylish-man-flat-vector-profile-picture-ai-generated_606187-310.jpg",
    collaborationType: "Paid",
    engagement: 10000,
    media: [
      "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      "https://picsum.photos/200/300",
    ],
  },
  {
    name: "David Lee",
    handle: "@davidl",
    followers: 15000,
    reach: 25000,
    rating: "4.6",
    bio: "Tech geek and gadget reviewer. Helping you pick the best devices with honest reviews and hands-on experience.",
    jobsCompleted: 16,
    successRate: "94%",
    profilePic:
      "https://img.freepik.com/premium-photo/stylish-man-flat-vector-profile-picture-ai-generated_606187-310.jpg",
    collaborationType: "Unpaid",
    engagement: 5000,
    media: [
      "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      "https://picsum.photos/200/300",
    ],
  },
  {
    name: "Sophia Martinez",
    handle: "@sophiam",
    followers: 14000,
    reach: 26000,
    rating: "4.5",
    bio: "Travel blogger exploring the world and sharing my journey with all of you. Let's discover new places together!",
    jobsCompleted: 11,
    successRate: "92%",
    profilePic:
      "https://img.freepik.com/premium-photo/stylish-man-flat-vector-profile-picture-ai-generated_606187-310.jpg",
    collaborationType: "Paid",
    engagement: 4500,
    media: [
      "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      "https://picsum.photos/200/300",
    ],
  },
  {
    name: "Daniel Kim",
    handle: "@danielk",
    followers: 7000,
    reach: 14000,
    rating: "4.9",
    bio: "Gaming content creator and streamer. Join me for fun gaming sessions and exciting reviews!",
    jobsCompleted: 9,
    successRate: "100%",
    profilePic:
      "https://img.freepik.com/premium-photo/stylish-man-flat-vector-profile-picture-ai-generated_606187-310.jpg",
    collaborationType: "Unpaid",
    engagement: 3500,
    media: [
      "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      "https://picsum.photos/200/300",
    ],
  },
  {
    name: "Olivia Harris",
    handle: "@oliviah",
    followers: 18000,
    reach: 29000,
    rating: "4.7",
    bio: "Fitness and wellness coach helping you live your best, healthy life. Join me for tips and motivation!",
    jobsCompleted: 13,
    successRate: "96%",
    profilePic:
      "https://img.freepik.com/premium-photo/stylish-man-flat-vector-profile-picture-ai-generated_606187-310.jpg",
    collaborationType: "Paid",
    engagement: 6500,
    media: [
      "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      "https://picsum.photos/200/300",
    ],
  },
  {
    name: "Tom Edwards",
    handle: "@tome",
    followers: 20000,
    reach: 32000,
    rating: "4.6",
    bio: "Photographer and visual storyteller capturing the beauty of the world. Let’s create something amazing!",
    jobsCompleted: 17,
    successRate: "91%",
    profilePic:
      "https://img.freepik.com/premium-photo/stylish-man-flat-vector-profile-picture-ai-generated_606187-310.jpg",
    collaborationType: "Unpaid",
    engagement: 7000,
    media: [
      "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      "https://picsum.photos/200/300",
    ],
  },
  {
    name: "Sara Davis",
    handle: "@sarad",
    followers: 22000,
    reach: 35000,
    rating: "4.8",
    bio: "Mommy blogger sharing my parenting journey and tips for raising happy, healthy kids.",
    jobsCompleted: 19,
    successRate: "99%",
    profilePic:
      "https://img.freepik.com/premium-photo/stylish-man-flat-vector-profile-picture-ai-generated_606187-310.jpg",
    collaborationType: "Paid",
    engagement: 8000,
    media: [
      "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      "https://picsum.photos/200/300",
    ],
  },
  {
    name: "Ryan Walker",
    handle: "@ryanw",
    followers: 11000,
    reach: 21000,
    rating: "4.9",
    bio: "Entrepreneur and business coach helping people scale their businesses and achieve financial freedom.",
    jobsCompleted: 14,
    successRate: "97%",
    profilePic:
      "https://img.freepik.com/premium-photo/stylish-man-flat-vector-profile-picture-ai-generated_606187-310.jpg",
    collaborationType: "Unpaid",
    engagement: 5500,
    media: [
      "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      "https://picsum.photos/200/300",
    ],
  },
  {
    name: "Zoe White",
    handle: "@zoew",
    followers: 9000,
    reach: 18000,
    rating: "4.7",
    bio: "Pet lover and animal advocate. Sharing adorable pet stories and tips on animal care!",
    jobsCompleted: 10,
    successRate: "95%",
    profilePic:
      "https://img.freepik.com/premium-photo/stylish-man-flat-vector-profile-picture-ai-generated_606187-310.jpg",
    collaborationType: "Paid",
    engagement: 4500,
    media: [
      "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      "https://picsum.photos/200/300",
    ],
  },
  {
    name: "Lucas Moore",
    handle: "@lucasm",
    followers: 16000,
    reach: 24000,
    rating: "4.8",
    bio: "Outdoor enthusiast and adventurer. Let's explore the wilderness and live life on the edge!",
    jobsCompleted: 15,
    successRate: "93%",
    profilePic:
      "https://img.freepik.com/premium-photo/stylish-man-flat-vector-profile-picture-ai-generated_606187-310.jpg",
    collaborationType: "Unpaid",
    engagement: 6000,
    media: [
      "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      "https://picsum.photos/200/300",
    ],
  },
  {
    name: "Grace Clark",
    handle: "@gracec",
    followers: 13000,
    reach: 22000,
    rating: "4.6",
    bio: "Health and nutrition expert sharing tips for a balanced diet and active lifestyle.",
    jobsCompleted: 12,
    successRate: "94%",
    profilePic:
      "https://img.freepik.com/premium-photo/stylish-man-flat-vector-profile-picture-ai-generated_606187-310.jpg",
    collaborationType: "Paid",
    engagement: 5500,
    media: [
      "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      "https://picsum.photos/200/300",
    ],
  },
  {
    name: "Matt Thompson",
    handle: "@mattt",
    followers: 27000,
    reach: 38000,
    rating: "4.7",
    bio: "Comedian and entertainer bringing laughter and joy to your feed every day!",
    jobsCompleted: 21,
    successRate: "96%",
    profilePic:
      "https://img.freepik.com/premium-photo/stylish-man-flat-vector-profile-picture-ai-generated_606187-310.jpg",
    collaborationType: "Unpaid",
    engagement: 9500,
    media: [
      "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      "https://picsum.photos/200/300",
    ],
  },
  {
    name: "Chloe Baker",
    handle: "@chloeb",
    followers: 19000,
    reach: 28000,
    rating: "4.8",
    bio: "Interior designer sharing my love for beautiful spaces and functional home decor.",
    jobsCompleted: 16,
    successRate: "98%",
    profilePic:
      "https://img.freepik.com/premium-photo/stylish-man-flat-vector-profile-picture-ai-generated_606187-310.jpg",
    collaborationType: "Paid",
    engagement: 7000,
    media: [
      "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      "https://picsum.photos/200/300",
    ],
  },
  {
    name: "Ethan Roberts",
    handle: "@ethanr",
    followers: 21000,
    reach: 33000,
    rating: "4.9",
    bio: "Adventure photographer capturing breathtaking moments in nature. Join me for thrilling visuals!",
    jobsCompleted: 18,
    successRate: "100%",
    profilePic:
      "https://img.freepik.com/premium-photo/stylish-man-flat-vector-profile-picture-ai-generated_606187-310.jpg",
    collaborationType: "Unpaid",
    engagement: 8500,
    media: [
      "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      "https://picsum.photos/200/300",
    ],
  },
  {
    name: "Victoria Evans",
    handle: "@victoriae",
    followers: 23000,
    reach: 37000,
    rating: "4.7",
    bio: "Travel and lifestyle influencer inspiring others to live their dream life through experiences.",
    jobsCompleted: 20,
    successRate: "96%",
    profilePic:
      "https://img.freepik.com/premium-photo/stylish-man-flat-vector-profile-picture-ai-generated_606187-310.jpg",
    collaborationType: "Paid",
    engagement: 9000,
    media: [
      "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      "https://picsum.photos/200/300",
    ],
  },
];
