import { CalendarItem } from "@/components/content-calendar/types";
import { Attachment } from "@/shared-libs/firestore/trendly-pro/constants/attachment";
import { IImageGeneration } from "@/shared-libs/firestore/trendly-pro/models/contents";
import Colors from "@/shared-uis/constants/Colors";

/**
 * UI content status — adopts the full 6-value Firestore enum
 * (Draft / PendingReview / Approved / Scheduled / Posted / Rejected).
 * The string values are identical to the Firestore `ContentStatus` enum, so the
 * two are interchangeable without a mapping table.
 */
export type ContentStatus =
    | "draft"
    | "in_progress"
    | "review_pending"
    | "approved"
    | "scheduled"
    | "posted"
    | "rejected";

/** A single uploaded or AI-generated media asset attached to a content piece. */
export interface MediaAsset {
    /** Public URL of the asset (S3, via useAWSContext). */
    url: string;
    kind: "image" | "video";
    /** Pixel dimensions — used for per-type aspect-ratio enforcement (Phase 2). */
    width?: number;
    height?: number;
    /** Order within a carousel (0-based); undefined for single-asset types. */
    order?: number;
    /** Whether the asset was uploaded by the user or generated by AI. */
    source: "uploaded" | "generated";
}

/** A connected social account this content will be published / scheduled to. */
export interface SocialDestination {
    /** Matches `ISocialAccount.id` from `useBrandSocialContext`. */
    socialAccountId: string;
    platform: "instagram" | "facebook" | "youtube" | "linkedin" | "twitter";
    /** Cached for display so the picker/preview don't need to re-query. */
    username?: string;
}

export type ScheduleMode = "now" | "scheduled";

export interface ContentItem extends CalendarItem {
    status: ContentStatus;
    caption?: string;
    hashtags?: string;
    timeOfPosting?: string; // "HH:MM"
    script?: string;
    imagePrompt?: string;
    /** Final media files / carousel slides. Mirrors `IContent.attachments`. */
    attachments?: Attachment[];
    /** Live state of a backend-driven AI image-generation job, if any. */
    imageGeneration?: IImageGeneration;
    /** Target connected accounts for publish / schedule (Phase 4). */
    destinations?: SocialDestination[];
    /** Publish immediately or at `scheduledAt`. */
    scheduleMode?: ScheduleMode;
    /** Epoch ms when a scheduled post should go live. */
    scheduledAt?: number;
    /**
     * Per-platform published media ids, set by the backend once posted
     * (e.g. `{ instagram: "<mediaId>" }`). Mirrors `IContent.publishedIds`.
     * Used to look up the live post's analytics + comments.
     */
    publishedIds?: Record<string, string>;
    /** Permalink to the live post once posted. Mirrors `IContent.postedUrl`. */
    postedUrl?: string;
    isArchived: boolean;
    createdAt: string;
}

export const CONTENT_STATUS_LABELS: Record<ContentStatus, string> = {
    draft: "Draft",
    in_progress: "In Progress",
    review_pending: "Review Pending",
    approved: "Approved",
    scheduled: "Scheduled",
    posted: "Posted",
    rejected: "Rejected",
};

/** Full status set, in lifecycle order (for filters, legends, etc.). */
export const CONTENT_STATUS_ORDER: ContentStatus[] = [
    "draft",
    "in_progress",
    "review_pending",
    "approved",
    "scheduled",
    "posted",
    "rejected",
];

/**
 * The authoring funnel shown as Board columns. Pipeline-driven (`scheduled`,
 * `posted`) and review-flow (`rejected`) statuses are intentionally excluded —
 * see the Contents-page ticket. Drag targets are limited to this set.
 */
export const BOARD_CONTENT_STATUSES: ContentStatus[] = [
    "draft",
    "in_progress",
    "review_pending",
    "approved",
];

/**
 * Statuses a brand manager may set by hand. `scheduled` / `posted` are driven by
 * the publishing pipeline and `rejected` by the review flow — they are not part
 * of the manual toggle. (Workflow gating is finalized in Phase 6.)
 */
export const EDITABLE_CONTENT_STATUSES: ContentStatus[] = [
    "draft",
    "in_progress",
    "review_pending",
    "approved",
];

/**
 * Theme-aware foreground/background colors for a status badge or pill. Pulls from
 * the central palette so components carry no hardcoded hex values.
 */
export function contentStatusColors(
    status: ContentStatus,
    colors: ReturnType<typeof Colors>
): { fg: string; bg: string } {
    switch (status) {
        case "in_progress":
            return { fg: colors.statusInProgressFg, bg: colors.statusInProgressBg };
        case "review_pending":
            return { fg: colors.statusReviewFg, bg: colors.statusReviewBg };
        case "approved":
            return { fg: colors.statusApprovedFg, bg: colors.statusApprovedBg };
        case "scheduled":
            return { fg: colors.statusScheduledFg, bg: colors.statusScheduledBg };
        case "posted":
            return { fg: colors.statusPostedFg, bg: colors.statusPostedBg };
        case "rejected":
            return { fg: colors.statusRejectedFg, bg: colors.statusRejectedBg };
        case "draft":
        default:
            return { fg: colors.statusDraftFg, bg: colors.statusDraftBg };
    }
}

export const POPULAR_POSTING_TIMES = [
    { label: "7:00 AM", value: "07:00" },
    { label: "12:00 PM", value: "12:00" },
    { label: "5:00 PM", value: "17:00" },
    { label: "7:30 PM", value: "19:30" },
    { label: "9:00 PM", value: "21:00" },
];
